name: Create package on push to master

on:
  push:
    # tags:
    #   - '*'

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP without any shared extensions except mbstring
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: none
      - name: Build PHP Applicaiton
        run: php build.php
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta_build
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/deb4sh/pepperminty-wiki 
          labels: |
            org.opencontainers.image.title="Pepperminty Wiki"
            org.opencontainers.image.description="Pepperminty Wiki is a complete wiki engine contained in a single file."
            org.opencontainers.image.vendor="https://github.com/${{ github.repository_owner }}"
            org.label-schema.url="https://github.com/${{ github.repository_owner }}/Pepperminty-Wiki"
            org.label-schema.usage="https://github.com/${{ github.repository_owner }}/Pepperminty-Wiki/blob/main/README.md"
            org.label-schema.schema-version="1.0"
          tags: |
            type=schedule
            type=sha
      - name: Build Docker and push image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_build.outputs.tags }}
          labels: ${{ steps.meta_build.outputs.labels }}